### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by tariibaba** [Cside/notion-search#31]
Please [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to this repository to make it easier for other people to contribute and move this project forward.

I recommend using the popular MIT license, as its highly permissive nature will encourage more people to take part in this software's development and improve it in various ways.

**Comment by Cside** [comment]
Thanks for your good advice. [I added LICENSE](https://github.com/Cside/notion-search/pull/32/commits/7ae450ae312695487f03c623f4a5cee0b0bd969e) .
